### ISSUE TITLE
Port to newer/latest Rust nightly version

### ISSUE THREAD

**Issue by disconnect3d** [LiHRaM/taint#18]
I'm taking a look if this can be done quickly as I want to try out the taint tracking on a project that uses newer Rust version.

Relevant:
* https://github.com/rust-lang/compiler-team/issues/426
* https://github.com/rust-lang/rust/issues/100717
* https://rustc-dev-guide.rust-lang.org/diagnostics/translation.html
* https://github.com/rust-lang/rustc-dev-guide/blob/master/src/diagnostics/diagnostic-structs.md

FWIW:
* https://github.com/rust-lang/rust/issues/114885
*  https://github.com/rust-lang/rust/issues/114884

**Comment by disconnect3d** [comment]
Added a porting attempt in https://github.com/LiHRaM/taint/pull/19

**Comment by LiHRaM** [comment]
Should work as of https://github.com/LiHRaM/taint/commit/eb225ca3f01b29f400c99ca18f1602da4b48dd94

**Comment by LiHRaM** [comment]
Thanks @disconnect3d for getting this started! Appreciate it. :)
